language: php

php:
  - 7.1
  - 7.2
  - nightly

before_script:
  ## Notify Codeclimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  ## Composer
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-source --no-interaction

script:
  - phpunit -c phpunit.xml.dist

after_success:
  # Send test reporting to Codeclimate
  - ./cc-test-reporter after-build --debug
  # Send test reporting to Codecov.io
  - bash <(curl -s https://codecov.io/bash)

notifications:
    email:
        - ci@gotardo.es

branches:
  only:
    - master
    - dev
    - feature/*
    - release/*
