language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

before_script:
  ## Notify Codeclimate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  ## Composer
  - curl -s http://getcomposer.org/installer | php
  - composer install --prefer-source --no-interaction

script:
  - ./vendor/bin/phpunit -c phpunit.xml.dist

after_success:
  # Send test reporting to Codeclimate
  - ./cc-test-reporter after-build --debug
  # Send test reporting to Codecov.io
  - bash <(curl -s https://codecov.io/bash)
  # Send report to sonarcloud
  - wget https://sonarsource.bintray.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip
  - unzip sonar-scanner-cli-3.2.0.1227-linux.zip
  - rm sonar-scanner-cli-3.2.0.1227-linux.zip
  - ./sonar-scanner-cli-3.2.0.1227-linux/sonar-scanner -Dsonar.projectKey=ldf-gutenberg -Dsonar.organization=gotardo-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=SONAR_TOKEN

notifications:
    email:
        - ci@gotardo.es

branches:
  except:
    - legacy
    - experimental
